# Generated by Django 5.1.15 on 2026-09-25 20:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Department name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_code', models.CharField(editable=False, help_text='Human-readable code e.g. CIV-1001. Auto-generated on save.', max_length=20, unique=True, verbose_name='Issue code')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='issues/images/%Y/%m/', verbose_name='Photo')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('ai_category', models.CharField(blank=True, choices=[('Pothole', 'Pothole'), ('Garbage', 'Garbage'), ('Streetlight', 'Streetlight'), ('Water Leakage', 'Water Leakage'), ('Drainage', 'Drainage'), ('Road Damage', 'Road Damage'), ('Other', 'Other')], default='', max_length=50, verbose_name='AI suggested category')),
                ('ai_priority', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='', max_length=10, verbose_name='AI suggested priority')),
                ('ai_summary', models.TextField(blank=True, default='', verbose_name='AI summary')),
                ('ai_confidence', models.FloatField(blank=True, help_text='0.0–1.0 confidence score returned by the AI model.', null=True, verbose_name='AI confidence')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Reported at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('ai_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggested_issues', to='issues.department', verbose_name='AI suggested department')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='incidents.incident', verbose_name='Associated incident')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL, verbose_name='Reported by')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['-created_at'],
            },
        ),
    ]
