# Generated by Django 5.2.17 on 2026-09-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citysenseuser',
            name='officer_level',
            field=models.CharField(choices=[('STANDARD', 'Standard officer'), ('L1', 'Level 1 officer'), ('L2', 'Level 2 officer')], default='STANDARD', help_text='Escalation designation for admin accounts; citizens remain standard officers.', max_length=10, verbose_name='Officer level'),
        ),
    ]
