# Generated by Django 5.1.15 on 2026-09-25 20:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('REPORTED', 'Reported'), ('VERIFIED', 'Verified'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='', max_length=20, verbose_name='Previous status')),
                ('new_status', models.CharField(choices=[('REPORTED', 'Reported'), ('VERIFIED', 'Verified'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], max_length=20, verbose_name='New status')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Changed at')),
            ],
            options={
                'verbose_name': 'Incident status history',
                'verbose_name_plural': 'Incident status histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_code', models.CharField(editable=False, help_text='Human-readable code e.g. INC-1001. Auto-generated on save.', max_length=20, unique=True, verbose_name='Incident code')),
                ('title', models.CharField(max_length=255, verbose_name='Incident title')),
                ('category', models.CharField(choices=[('Pothole', 'Pothole'), ('Garbage', 'Garbage'), ('Streetlight', 'Streetlight'), ('Water Leakage', 'Water Leakage'), ('Drainage', 'Drainage'), ('Road Damage', 'Road Damage'), ('Other', 'Other')], default='Other', max_length=50, verbose_name='Category')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10, verbose_name='Priority')),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('VERIFIED', 'Verified'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='REPORTED', max_length=20, verbose_name='Status')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('severity_score', models.FloatField(blank=True, help_text='Computed by the severity pipeline. Higher = more urgent.', null=True, verbose_name='Severity score')),
                ('report_count', models.PositiveIntegerField(default=1, help_text='Number of citizen issues associated with this incident.', verbose_name='Report count')),
                ('resolution_notes', models.TextField(blank=True, default='', verbose_name='Resolution notes')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-created_at'],
            },
        ),
    ]
