# Generated by Django 5.2.17 on 2026-09-29 17:14

from datetime import timedelta

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_sla_configuration(apps, schema_editor):
    Incident = apps.get_model("incidents", "Incident")
    Configuration = apps.get_model("incidents", "IncidentSLAConfiguration")
    database = schema_editor.connection.alias
    defaults = {
        "CRITICAL": (1, 1),
        "HIGH": (3, 2),
        "MEDIUM": (7, 3),
        "LOW": (14, 5),
    }
    for priority, (resolution_days, l2_after_days) in defaults.items():
        Configuration.objects.using(database).get_or_create(
            priority=priority,
            category="",
            defaults={"resolution_days": resolution_days, "l2_after_days": l2_after_days},
        )

    for incident in Incident.objects.using(database).filter(sla_started_at__isnull=True).iterator():
        started_at = incident.created_at
        configuration = Configuration.objects.using(database).filter(
            priority=incident.priority, category="",
        ).first()
        days = configuration.resolution_days if configuration else 7
        Incident.objects.using(database).filter(pk=incident.pk).update(
            sla_started_at=started_at,
            resolution_deadline=started_at + timedelta(days=days),
        )


def remove_seeded_sla_configuration(apps, schema_editor):
    Configuration = apps.get_model("incidents", "IncidentSLAConfiguration")
    Configuration.objects.using(schema_editor.connection.alias).filter(category="").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incident_resolution_image'),
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='escalation_level',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('L1', 'Level 1'), ('L2', 'Level 2')], default='NORMAL', max_length=10, verbose_name='Escalation level'),
        ),
        migrations.AddField(
            model_name='incident',
            name='l1_escalated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='L1 escalated at'),
        ),
        migrations.AddField(
            model_name='incident',
            name='l2_escalated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='L2 escalated at'),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolution_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resolution deadline'),
        ),
        migrations.AddField(
            model_name='incident',
            name='sla_overdue',
            field=models.BooleanField(default=False, verbose_name='SLA overdue'),
        ),
        migrations.AddField(
            model_name='incident',
            name='sla_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SLA started at'),
        ),
        migrations.AddField(
            model_name='incidentstatushistory',
            name='assigned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_escalations_from', to=settings.AUTH_USER_MODEL, verbose_name='Previously assigned officer'),
        ),
        migrations.AddField(
            model_name='incidentstatushistory',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_escalations_to', to=settings.AUTH_USER_MODEL, verbose_name='Escalated to officer'),
        ),
        migrations.AddField(
            model_name='incidentstatushistory',
            name='department_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_escalations_from', to='issues.department', verbose_name='Original department'),
        ),
        migrations.AddField(
            model_name='incidentstatushistory',
            name='department_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_escalations_to', to='issues.department', verbose_name='Routed department'),
        ),
        migrations.AddField(
            model_name='incidentstatushistory',
            name='event_type',
            field=models.CharField(choices=[('STATUS', 'Status change'), ('ESCALATION', 'SLA escalation')], default='STATUS', max_length=12, verbose_name='Event type'),
        ),
        migrations.AddField(
            model_name='incidentstatushistory',
            name='new_escalation_level',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('L1', 'Level 1'), ('L2', 'Level 2')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='incidentstatushistory',
            name='previous_escalation_level',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('L1', 'Level 1'), ('L2', 'Level 2')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='incidentstatushistory',
            name='reason',
            field=models.TextField(blank=True, default='', verbose_name='Audit reason'),
        ),
        migrations.CreateModel(
            name='IncidentSLAConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('category', models.CharField(blank=True, choices=[('Pothole', 'Pothole'), ('Garbage', 'Garbage'), ('Streetlight', 'Streetlight'), ('Water Leakage', 'Water Leakage'), ('Drainage', 'Drainage'), ('Road Damage', 'Road Damage'), ('Other', 'Other')], default='', max_length=50)),
                ('resolution_days', models.PositiveSmallIntegerField(default=7, help_text='Calendar days from SLA start until the first escalation.', validators=[django.core.validators.MinValueValidator(1)])),
                ('l2_after_days', models.PositiveSmallIntegerField(default=3, help_text='Calendar days after L1 escalation before routing to L2.', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Incident SLA configuration',
                'verbose_name_plural': 'Incident SLA configurations',
                'ordering': ('priority', 'category'),
                'constraints': [models.UniqueConstraint(fields=('priority', 'category'), name='unique_incident_sla_priority_category')],
            },
        ),
        migrations.RunPython(seed_sla_configuration, remove_seeded_sla_configuration),
    ]
